Small spelling mistake causing compilation to fail
Small spelling mistake causing compilation to fail when  MPI="off". Currently still fails due to another line 

search.cxx: In function ‘Int_t* SearchFullSet(Options&, Int_t, NBody::Particle*&, Int_t&)’:
search.cxx:94:14: error: cannot convert ‘short int*’ to ‘Int_t* {aka long long int*}’ in assignment
     storetype=new short[nbodies];